version: "3.7"

networks:
    books:
        name: books-external

services:
    books-admin-client:
        build:
            context: ../..
            dockerfile: docker/development/Dockerfile
        networks:
            - books
        volumes:
            - ../../:/app
            - "books-admin-node_modules:/app/node_modules"
        ports:
            - "3000:3000"
        command: '/app/tools/run-client.sh'
        working_dir: /app

volumes:
    books-admin-node_modules:
